name: Update Cruise Tracklines
on: [workflow_dispatch]
jobs:
    Update-Tracklines:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'
                cache: 'pip'
            - run: pip install -r requirements.txt
            - name: Run Update Script
              env:
                CCHDO_AUTH_API_KEY: ${{ secrets.CCHDO_AUTH_TOKEN }}
              run: |
                python trackline/__main__.py