name: Add Missing Cruise Sumfiles
on: 
    schedule:
        # Noon UTC is about 5am San Diego time
        - cron: "10 12 * * *"
    workflow_dispatch:

env:
  COLUMNS: 120

jobs:
    Update-Sumfiles:
        runs-on: ubuntu-24.04-arm
        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                enable-cache: true

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            - name: Check and Add CCHDO Sumfiles
              env:
                CCHDO_AUTH_API_KEY: ${{ secrets.CCHDO_AUTH_TOKEN }}
              run: |
                echo "::group::Install Dependencies"
                uv run sumfile_update/__main__.py