name: Update Cruise Tracklines
on: 
    schedule:
        # Noon UTC is about 5am San Diego time
        - cron: "4 12 * * *"
    workflow_dispatch:
jobs:
    Update-Tracklines:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'
                cache: 'pip'
            - run: pip install -r requirements.txt
            - name: Check and Update CCHDO Tracklines
              env:
                CCHDO_AUTH_API_KEY: ${{ secrets.CCHDO_AUTH_TOKEN }}
              run: |
                python trackline/__main__.py