name: Update Cruise Tracklines
on: 
    schedule:
        # Noon UTC is about 5am San Diego time
        - cron: "4 12 * * *"
    workflow_dispatch:
jobs:
    Update-Tracklines:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                enable-cache: true

            # uv docs suggest using the gh actions to install python is faster
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            # Should just install all the deps
            - name: Check and Update CCHDO Tracklines
              env:
                CCHDO_AUTH_API_KEY: ${{ secrets.CCHDO_AUTH_TOKEN }}
              run: |
                uv run trackline/__main__.py