name: Update CF Derived Files
on: 
    schedule:
        # Noon UTC is about 5am San Diego time
        - cron: "50 13 * * *"
    workflow_dispatch:

env:
  COLUMNS: 120

jobs:
    Update-CF-Derived:
        runs-on: ubuntu-24.04-arm
        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                enable-cache: true

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            - name: Check and Update CCHDO Bottle Files
              env:
                CCHDO_AUTH_API_KEY: ${{ secrets.CCHDO_AUTH_TOKEN }}
              run: |
                echo "::group::Install Dependencies"
                uv run controlled_file_generator/__main__.py bottle
            - name: Check and Update CCHDO CTD Files
              env:
                CCHDO_AUTH_API_KEY: ${{ secrets.CCHDO_AUTH_TOKEN }}
              run: |
                echo "::group::Install Dependencies"
                uv run controlled_file_generator/__main__.py ctd